excluded:
  - Pods

disabled_rules:
  - force_try
  - force_cast
  - multiple_closures_with_trailing_closure
  - private_over_fileprivate
  - type_body_length
  - function_parameter_count
  - line_length
  - file_length
  - weak_delegate
  - class_delegate_protocol
  - syntactic_sugar
  - implicit_getter
  - shorthand_operator
  - notification_center_detachment
  - cyclomatic_complexity

type_name:
  allowed_symbols:
    - _
  validates_start_with_lowercase: false

function_body_length:
  warning: 100
  error: 150

line_length:
  - 150
  - 160

file_length:
  - 500
  - 550

identifier_name:
  min_length:
    error: 3
  validates_start_with_lowercase: true
  allowed_symbols:
    - _
  excluded:
    - id
    - PI
    - UG
    - KE
    - NO
    - to
    - os
    - on
    - y1
    - x2
    - i
    - y
    - x
    - a
    - b
    - c
    - d
    - h
    - fb
    - gl

large_tuple:
  warning: 5
  error: 8
